---
apiVersion: v1
kind: Service
metadata:
  name: interceptor
spec:
  type: NodePort
  ports:
    - portocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: interceptor
---
apiVersion: v1
kind: Pod
metadata:
  name: interceptor
  labels:
    app: interceptor
spec:
  containers:
    - name: interceptor
      image: "{{ .Values.image.componentName }}:{{ .Values.image.tag }}"
      ports:
        - containerPort: {{ .Values.service.port }}
          protocol: TCP
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true